INFO:root:gpu device = cuda:0
Traceback (most recent call last):
  File "main.py", line 278, in <module>
    save_model_str=get('run_dir'))
  File "main.py", line 214, in create_run_ensemble
    ensemble_model = EnsembleModel(trained_models, dense_units=128, out_size=train_dataset.n_classes)
TypeError: __init__() got an unexpected keyword argument 'dense_units'
