/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/home/rkohli/aml-project/PC-DARTS/train.py:131: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  nn.utils.clip_grad_norm(model.parameters(), grad_clip)
--- Logging error ---
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/home/rkohli/anaconda3/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/home/rkohli/anaconda3/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/home/rkohli/anaconda3/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: must be real number, not tuple
Call stack:
  File "darts-es.py", line 176, in <module>
    worker.run_es()
  File "darts-es.py", line 168, in run_es
    results = entropy_search(self.compute, lower, upper, num_iterations=iterations, cs=cs, min_budget=self.min_budget, max_budget=self.max_budget)
  File "/home/rkohli/aml-project/PC-DARTS/fmin/entropy_search.py", line 120, in entropy_search
    x_best, f_min = bo.run(num_iterations)
  File "/home/rkohli/aml-project/PC-DARTS/solver/bo_hb.py", line 147, in run
    y[i], self.time_func_evals[i])
Message: 'Configuration achieved a performance of %f in %f seconds'
Arguments: ((2.3334618638356526,), 751.9854938983917)
--- Logging error ---
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/home/rkohli/anaconda3/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/home/rkohli/anaconda3/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/home/rkohli/anaconda3/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: must be real number, not tuple
Call stack:
  File "darts-es.py", line 176, in <module>
    worker.run_es()
  File "darts-es.py", line 168, in run_es
    results = entropy_search(self.compute, lower, upper, num_iterations=iterations, cs=cs, min_budget=self.min_budget, max_budget=self.max_budget)
  File "/home/rkohli/aml-project/PC-DARTS/fmin/entropy_search.py", line 120, in entropy_search
    x_best, f_min = bo.run(num_iterations)
  File "/home/rkohli/aml-project/PC-DARTS/solver/bo_hb.py", line 147, in run
    y[i], self.time_func_evals[i])
Message: 'Configuration achieved a performance of %f in %f seconds'
Arguments: ((2.3334618638356526,), 751.9854938983917)
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "darts-es.py", line 176, in <module>
    worker.run_es()
  File "darts-es.py", line 168, in run_es
    results = entropy_search(self.compute, lower, upper, num_iterations=iterations, cs=cs, min_budget=self.min_budget, max_budget=self.max_budget)
  File "/home/rkohli/aml-project/PC-DARTS/fmin/entropy_search.py", line 120, in entropy_search
    x_best, f_min = bo.run(num_iterations)
  File "/home/rkohli/aml-project/PC-DARTS/solver/bo_hb.py", line 150, in run
    best_idx = np.argmin(y)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: '<' not supported between instances of 'tuple' and 'int'
