INFO:root:gpu device = cuda:0
Traceback (most recent call last):
  File "main.py", line 296, in <module>
    save_model_str=get('run_dir'))
  File "main.py", line 216, in create_run_ensemble
    summary(ensemble_model, input_size=train_dataset.images.shape)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rkohli/aml-project/src/model.py", line 295, in forward
    model_out = model(x)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rkohli/aml-project/src/model.py", line 247, in forward
    s0 = s1 = self.stem(input)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 24 1 3 3, expected input[2, 232365, 28, 28] to have 1 channels, but got 232365 channels instead
