INFO:root:gpu device = cuda:0
Traceback (most recent call last):
  File "main.py", line 296, in <module>
    save_model_str=get('run_dir'))
  File "main.py", line 216, in create_run_ensemble
    summary(ensemble_model, input_size=self.images.shape)
NameError: name 'self' is not defined
