Traceback (most recent call last):
  File "main.py", line 352, in <module>
    os.mkdir(exp_dir)
FileExistsError: [Errno 17] File exists: './EXP3'
