INFO:root:gpu device = cuda:0
INFO:root:epoch 0 lr 4.442566e-02
Traceback (most recent call last):
  File "main.py", line 296, in <module>
    save_model_str=get('run_dir'))
  File "main.py", line 238, in create_run_ensemble
    train_acc, train_obj = ensemble_train(train_loader, ensemble_model, criterion, optimizer, grad_clip=ensemble_config['grad_clip_value'])
  File "/home/rkohli/aml-project/src/train.py", line 150, in ensemble_train
    for i_model in model.models():
TypeError: 'list' object is not callable
